[package]
name = "Tandem"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.1"
tungstenite = { version = "0.26.2" }
chess = "3.2.0"
serde_json = "1.0.140"